### ISSUE TITLE
MFXDatePicker not found in Scene Builder

### ISSUE THREAD

**Issue by vinimaartiins** [palexdev/MaterialFX#155] opened 2022-03-10 00:51 UTC
Hello,

First of all I really appreciate your work, it's awesome. Well, I have been faced a issue in my project when I searched for MFXDatePicker on Scene builder but I did not find it (11.13.2).

![image](https://user-images.githubusercontent.com/58339268/157564856-5fd91d19-71a5-4745-a32a-64eb374479d9.png)

I only can see MFXDatePicker on Scene Builder if I search for 11.12.0 or older

![image](https://user-images.githubusercontent.com/58339268/157565133-f70392f5-91ca-4094-87a5-6cac0011444c.png)

**Comment by palexdev** [comment] 2022-03-10 01:15
Closing as duplicate of #129

**Closed by palexdev** 2022-03-10 01:15 UTC
