### ISSUE TITLE
MfxTableView pagination customization

### ISSUE THREAD

**Issue by warmuuh** [palexdev/MaterialFX#92] opened 2021-08-12 06:57 UTC
It would be neat to have the option to disable pagination controls and just have a plain table. 
Maybe the solution is to stick with the legacy-version but as it is called legacy, i dont like to use it ;)

**Comment by palexdev** [comment] 2021-08-12 08:41
An idea that I have already had for some time but it's not possible on the current table because pagination controls are needed for navigation

I'd say this is a duplicate of #24

A scrollable MFXTableView would not have pagination controls and would be more similar to the JavaFX's one

I don't know when I'll implement that tough so in the meanwhile if you really can't have pagination controls you should use the legacy one.

**Comment by palexdev** [comment] 2022-01-23 16:32
Tables have been reviewed in latest release
Now there are two versions, one is scrollable the other is paginated

**Closed by palexdev** 2022-01-23 16:32 UTC
Labels: enhancement, staging
