### ISSUE TITLE
Local dev path in the gradle build file

### ISSUE THREAD

**Issue by chimp1984** [palexdev/MaterialFX#35] opened 2021-05-26 16:44 UTC
There is a local dev path in the gradle build file:

```
task copyJar(type: Copy) {
    from jar
    into 'C:/Users/thund/AppData/Roaming/Scene Builder/Library'
}
```

**Comment by mica-alex** [comment] 2021-06-06 13:43
As a suggestion, you likely can change to the following so it does not reference a user-specific folder but still works for you

```
task copyJar(type: Copy) {
    from jar
    into '${System.properties['user.home']}${File.separator}AppData${File.separator}Roaming${File.separator}Scene Builder${File.separator}Library'
}
```

https://github.com/palexdev/MaterialFX/blob/8483213ba19ffc754881f0bf006dc97e6309dfd4/materialfx/build.gradle#L66-L69

**Comment by palexdev** [comment] 2021-06-06 14:19
Still not cross-platform
I was thinking of fixing it by also checking the OS
The problem is that I know Windows and Linux paths, but I can't check on Mac
So eventually I won't add Mac support, at least until someone tells me where SceneBuilder library folder is on MacOS

**Comment by mica-alex** [comment] 2021-06-06 18:07
I just did a fresh install of Scene Builder on macOS and this is the folder where it puts .jars: `/Users/[username]/Library/Application Support/Scene Builder/Library`.

Similar to Linux, the user's home folder can just be shortened to `~`, giving `~/Library/Application Support/Scene Builder/Library` as the macOS path.

**Comment by palexdev** [comment] 2021-06-06 18:21
@mica-alex Thank you very much, the fix will be included in the upcoming update

**Comment by palexdev** [comment] 2021-06-07 13:05
Fixed in latest release

**Closed by palexdev** 2021-06-07 13:05 UTC
