### ISSUE TITLE
Designing in TableViews

### ISSUE THREAD

**Issue by SaadSidd29** [palexdev/MaterialFX#176] opened 2022-04-14 09:48 UTC
Hi,

I cannot see any MFXTableViews in my scene builder with version MFX 11.13.5. I can only see MFXLegacyTableView
Also is there any documentation on how to make tables as it has no columns and I need to have columns and filters.
Please look into the image for all elements I am having

Thanks,
Saad

![image](https://user-images.githubusercontent.com/90084667/163360010-7b15b9d9-9b2d-4763-bcb0-2651d9e5a6b5.png)

**Comment by SaadSidd29** [comment] 2022-04-14 10:58
Ok, I got it, I have now added VirtualizedFX, and it's there :) 

Do you have any documentation on how to add rows to the table because I need to fetch database and into this table

**Comment by kdelgado98** [comment] 2022-04-15 20:08
I have exactly the same problem, I don't know how to add columns to the mfxtableview

**Comment by SaadSidd29** [comment] 2022-04-16 10:19
@kdelgado98  If you want to add columns then you can do something like this.

mfxtable is your table name.


`MFXTableColumn firstName = new MFXTableColumn("FirstName");
MFXTableColumn lastName = new MFXTableColumn("LastName");
mfxtable.getTableColumns().add(firstName);
mfxtable.getTableColumns().add(lastName);`


I am having an issue with the data population.
Not able to map with setCellValueFactory

@palexdev Need your urgent advisory

Thanks,
Saad

**Comment by palexdev** [comment] 2022-04-16 10:32
I'm sorry, this week has been crazy I've been busy the whole time.

So, configuring MFXTableView is pretty easy.
Let's say my model is a Person with name, age and career.

First you have to create the MFXTableColumns you need
```java
MFXTableColumn<Person> nameColumn = new MFXTableColumn<>("Name");
MFXTableColumn<Person> ageColumn = new MFXTableColumn<>("Age");
MFXTableColumn<Person> careerColumn = new MFXTableColumn<>("Career");
```

Then you must tell the columns how to represent the data, how to create the corresponding cells so:
```java
nameColumn.setRowCellFactory(person -> new MFXTableRowCell(Person::getName));
ageColumn.setRowCellFactory(person -> new MFXTableRowCell(Person::getAge));
careerColumn.setRowCellFactory(person -> new MFXTableRowCell(Person::getCareer));
```

That's it, now the two remaining steps is to add the columns to the table so:
```java
table.getTableColumns().addAll(nameColumn, ageColumn, careerColumn);
```

And add the items to the table:
```java
table.setItems(people);
OR
table.getItems().setAll(people);
```

A full example is here in the demo: [TableViewsController.java](https://github.com/palexdev/MaterialFX/blob/main/demo/src/main/java/io/github/palexdev/materialfx/demo/controllers/TableViewsController.java)

**Comment by SaadSidd29** [comment] 2022-04-16 10:36
@palexdev Thanks so much ... 
Yeah, I can understand, same here with me.

Will try this :)

Thanks,
Saad

**Comment by palexdev** [comment] 2022-04-16 10:38
@SaadSidd29 no problem, thanks for using MaterialFX ;)

I'll leave the issue open for a bit so if you encounter any other problem let me now and I'll answer asap

**Comment by SaadSidd29** [comment] 2022-04-16 10:39
Sure Thanks :)

**Comment by SaadSidd29** [comment] 2022-04-16 11:46
Great! I have done it 👍 
Filters are looking amazing. Great Work

Hats off bro :)

Leaving this open for @kdelgado98 If you need any help you can ask here or can contact me

**Comment by palexdev** [comment] 2022-04-16 12:07
> Great! I have done it 👍 
> Filters are looking amazing. Great Work
> 
> Hats off bro :)
> 
> Leaving this open for @kdelgado98 If you need any help you can ask here or can contact me

Thanks
Well to be fair the table still needs some adjustments on the layout side, scrollbars need to be properly fixed but it's the next thing I'm gonna do, I'm working on it right now

**Comment by SaadSidd29** [comment] 2022-04-16 19:27
Can you advice me on how to make a specific row of a table highlighted when a button is pressed.
I have been trying to do this on normal TreeTableView but no luck.

Functionality refers to requirement that when a row is being read and processed, it should be marked as RED and rest GREEN.

**Comment by palexdev** [comment] 2022-04-17 22:10
Well there are several ways you could achieve this
Two come to my mind:
1) The easiest one in my opinion if you don't care about selection. You could use the selection state of the rows to indicate the state. Selected -> Being processed, Not selected -> Not processed. When you take an item that needs to be processed use the table' selection model to select the item. Of course you need a stylesheet to customize the colors. Default background would be RED and when selected GREEN
2) This is more tricky and requires more code and knowledge. You could design custom MFXTableRows and create new PseudoClasses specifically for your task, so maybe ":processing" and then of course a stylesheet

**Comment by mahfoud09** [comment] 2022-04-20 11:31
can i setGraphic in cell  MFXPaginatedTableView (for exemple : MFXButton ) ?

**Comment by palexdev** [comment] 2022-04-20 11:37
> can i setGraphic in cell  MFXPaginatedTableView (for exemple : MFXButton ) ?
> 

Read the documentation [MFXTableRowCell](https://github.com/palexdev/MaterialFX/blob/main/materialfx/src/main/java/io/github/palexdev/materialfx/controls/cell/MFXTableRowCell.java)
MaterialFX documentation is gold compared to most libraries out there
I'm not a teacher guys you must learn just like I did ;)


Sidenote: this issue will be closed by the end of the week since there hasn't been any useful feedback in the last few days

**Comment by kdelgado98** [comment] 2022-04-23 17:00
> 



> Great! I have done it 👍 Filters are looking amazing. Great Work
> 
> Hats off bro :)
> 
> Leaving this open for @kdelgado98 If you need any help you can ask here or can contact me

Thanks i've been too busy this week but thanks for leave this open for me 😅, i will work on it asap and if i have any trouble i will contact you , thanks again

**Comment by mahfoud09** [comment] 2022-04-24 13:22
thanks @palexdev
one more question , item not updated when page changed in MFXPaginatedTableView

**Comment by palexdev** [comment] 2022-04-24 13:26
> thanks @palexdev
> one more question , item not updated when page changed in MFXPaginatedTableView 

Share a minimal reproducible example please so that I can test it
It could depend from various things

**Comment by mahfoud09** [comment] 2022-04-24 14:04
> > thanks @palexdev
> > one more question , item not updated when page changed in MFXPaginatedTableView
> 
> Share a minimal reproducible example please so that I can test it It could depend from various things

i have a table of products and i put a tooltip on each row 
when i change the page the product change only on tableview but the real product not changed  


![image](https://user-images.githubusercontent.com/43850998/164980074-be35d0bd-3147-461e-be68-279c27b88ec1.png)
![image](https://user-images.githubusercontent.com/43850998/164980232-e8510fa6-079d-41ea-b0ea-15791dabaf09.png)

**Comment by palexdev** [comment] 2022-04-25 09:43
> > > thanks @palexdev
> > > one more question , item not updated when page changed in MFXPaginatedTableView
> > 
> > 
> > Share a minimal reproducible example please so that I can test it It could depend from various things
> 
> i have a table of products and i put a tooltip on each row when i change the page the product change only on tableview but the real product not changed
> 
> ![image](https://user-images.githubusercontent.com/43850998/164980074-be35d0bd-3147-461e-be68-279c27b88ec1.png) ![image](https://user-images.githubusercontent.com/43850998/164980232-e8510fa6-079d-41ea-b0ea-15791dabaf09.png)

I don't think it's related to MaterialFX, it depends on how you implemented the tooltip on the row.
Rows do not map to one and only one item, they are reused so you must update the tooltip when the row's data changes

**Comment by palexdev** [comment] 2022-04-25 09:44
Anyway, as I said I see no more useful feedback/discussion here specifically related to MaterialFX, so I'm closing this issue

**Closed by palexdev** 2022-04-25 09:44 UTC
Labels: not an issue

**Comment by ramprajapat94** [comment] 2023-05-28 06:58
Hello @palexdev ,
Firstly, thank you so much for giving MaterialFX to JavaFX developers.

Secondly, I have gone through this solution: https://github.com/palexdev/MaterialFX/issues/176#issuecomment-1100632899.
Just wanted to confirm that is there no way to customize/add columns (MFXTableColumn) to MFXTableView via scene builder?

Thanks
